#!/usr/bin/env node
import { mkdirSync, writeFileSync } from "node:fs";import { dirname, resolve } from "node:path";
function argument(name){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined;}
const raw=argument("--base-url")??process.env.PRODUCTION_BASE_URL;if(!raw)throw new Error("Informe --base-url ou PRODUCTION_BASE_URL.");const baseUrl=new URL(raw);if(baseUrl.protocol!=="https:"&&!["localhost","127.0.0.1"].includes(baseUrl.hostname))throw new Error("O smoke test remoto exige HTTPS.");
const expectedCommit=argument("--expected-commit")??process.env.EXPECTED_COMMIT;const secret=process.env.HEALTHCHECK_SECRET?.trim();if(!secret)throw new Error("HEALTHCHECK_SECRET é obrigatório para o smoke test.");const checks=[];
async function run(name,operation){const started=Date.now();try{await operation();checks.push({name,status:"pass",durationMs:Date.now()-started});}catch(error){checks.push({name,status:"fail",durationMs:Date.now()-started,message:error instanceof Error?error.message.slice(0,300):"unknown_error"});}}
async function request(path,init={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{return await fetch(new URL(path,baseUrl),{redirect:"manual",cache:"no-store",...init,signal:controller.signal});}finally{clearTimeout(timeout);}}
await run("liveness",async()=>{const response=await request("/api/health/live");if(response.status!==200)throw new Error(`status_${response.status}`);const payload=await response.json();if(payload.status!=="ok"||payload.service!=="orienta")throw new Error("invalid_payload");if(expectedCommit&&!String(payload.commit).startsWith(expectedCommit.slice(0,7)))throw new Error(`unexpected_commit_${String(payload.commit).slice(0,12)}`);});
await run("readiness",async()=>{const response=await request("/api/health/ready",{headers:{authorization:`Bearer ${secret}`}});const payload=await response.json();if(response.status!==200||payload.status!=="ready"){const failed=Array.isArray(payload.checks)?payload.checks.filter((item)=>item.status!=="pass").map((item)=>item.name).join(","):"unknown";throw new Error(`not_ready:${failed}`);}});
await run("login_page",async()=>{const response=await request("/");if(response.status!==200)throw new Error(`status_${response.status}`);if(!(response.headers.get("content-type")??"").includes("text/html"))throw new Error("not_html");});
await run("security_headers",async()=>{const response=await request("/");for(const [header,required] of new Map([["x-content-type-options","nosniff"],["x-frame-options","DENY"],["referrer-policy","strict-origin-when-cross-origin"]]))if(response.headers.get(header)!==required)throw new Error(`missing_or_invalid_${header}`);const csp=response.headers.get("content-security-policy")??"";if(!csp.includes("default-src 'self'")||!csp.includes("frame-ancestors 'none'"))throw new Error("invalid_content_security_policy");if(baseUrl.protocol==="https:"&&!response.headers.get("strict-transport-security"))throw new Error("missing_hsts");});
const report={checkedAt:new Date().toISOString(),baseOrigin:baseUrl.origin,expectedCommit:expectedCommit?.slice(0,12)??null,status:checks.every((check)=>check.status==="pass")?"pass":"fail",checks};const reportPath=resolve(process.env.SMOKE_REPORT??"var/release/smoke-report.json");mkdirSync(dirname(reportPath),{recursive:true});writeFileSync(reportPath,`${JSON.stringify(report,null,2)}\n`,{mode:0o600});console.log(JSON.stringify(report,null,2));if(report.status!=="pass")process.exit(1);
